### PR TITLE
Unnecessary Code

### PR DESCRIPTION
**Pull request by Kek5chen**
Compiler does an impossible cmp jnz if you use the else exit as its unneeded anyways because checkUsername could only return 0 or 1. We changed it so that checkUsername can also return 2. This should be a more standardized approach since you should never let a function that is supposed to return something exit the program if it isnt in mind of the function. "checkUsername" is there to check a username, not quit the program. We already wondered why you dont return a bool from the function while we reverse engineered the checkUsername function. Now we get what you tried to do, and there you go, we made it make sense.

This also removes unnecessarily compiled code for this.

This is some disassembled output from IDA Pro so you can make an educated guess on whats happening under the hood if you do it like it was before.

`.text:0000000000401608                 mov     [rbp+bool_username_valid], eax`

`.text:000000000040160B                 cmp     [rbp+bool_username_valid], 0`

`.text:000000000040160F                 jnz     short loc_40164A`

`...`

`.text:000000000040164A loc_40164A:                             ; CODE XREF: main+44↑j`

`.text:000000000040164A                 cmp     [rbp+bool_username_valid], 1`

`.text:000000000040164E                 jnz     short loc_40166C`

`...`

`.text:000000000040166C loc_40166C:                             ; CODE XREF: main+83↑j`

`.text:000000000040166C                 mov     ecx, 0          ; Code`

`.text:0000000000401671                 call    exit`

Also, we know, noone cares. But, actually we do. We only just want the best for you and just want you to learn something while programming. Everyone makes mistakes, and these small mistakes can tilt a whole mindset. So have fun and maybe try to understand why this makes sense.

We wish you a nice day

### CODE REVIEW

**Comment by Kek5chen** [comment]
Just, dont ask why we would care about this, this much.

**Comment by TKLinux966** [comment]
Thank you for reviewing my code. 
I'll fix my code.
I really appreciate your advice.

**Comment by Kek5chen** [comment]
If you just merge this pull request everything is fixed.

**Comment by Kek5chen** [comment]
But i guess copy pasting it works too?

**Comment by Kek5chen** [comment]
Also, if you'd like to reverse something more advanced. You could try out our crackme: https://crackmes.one/crackme/617965c733c5d4329c345330

**Comment by TKLinux966** [comment]
I did copy pasting.
Thank you. I'll give it a short.

**Pull request closed without merging**
